### ISSUE TITLE
CoffeeScript source map

### ISSUE THREAD

**Issue by satyrius** [iampeter/backbone-marionette-gulp-seed#1]
You have a nice gulp file, thanks! The one thing is missing: it is always convenient to see exact line of original source file when some javascript errors happens in a browser. So I've tried to apply some existing gulp plugins to achieve this feature, but I had no success. Could you help?

**Comment by iampeter** [comment]
thanks, glad it's helpful. you're right, souce maps should be on. actually browserify has an option for this. I've switched it on and committed:
https://github.com/iampeter/backbone-marionette-gulp-seed/commit/c618378f2ddc71cabdf4ca8c68c0ba63d0ca0d81

**Comment by satyrius** [comment]
Thanks @iampeter, this helps!

**Comment by iampeter** [comment]
@satyrius np. added the development / production separation in the recent commit, so everything is uglified / minified for production and keeping source clear and source maps on for development

**Comment by satyrius** [comment]
Yeah, I saw it, thaks
